/*
 * This source file was generated by the Gradle 'init' task
 */
package com.college.fcar;

public class FcarApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new FcarApplication().getGreeting());
    }
}
