spring.application.name=fcar

# DATABASE
# TODO: change these to env variables, so we don't leak it in future
spring.datasource.url = jdbc:postgresql://localhost:5432/fcar
spring.datasource.username = fcar_user
spring.datasource.password = 2ddfc7588e60ddd7b2f97cd453d750e79037c8b9e16113fb5768e365154905de
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true

# TODO: restrict permissions in future
spring.flyway.enabled=true