/*
 * This source file was generated by the Gradle 'init' task
 */
package com.college.fcar;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FcarApplicationTest {
    @Test void appHasAGreeting() {
        FcarApplication classUnderTest = new FcarApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
